name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Site Repository ðŸ›Žï¸
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: site

      - name: Checkout Theme Repository ðŸŽ¨
        uses: actions/checkout@v4
        with:
          repository: copyninja/pelican-simple
          path: pelican-simple

      - name: Checkout Pelican Plugins ðŸ”Œ
        run: |
          git clone --depth=1 https://github.com/getpelican/pelican-plugins.git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pelican markdown typogrify beautifulsoup4
          pip install pelican-youtube pelican-minification pelican-render-math
          apt-get install make -y

      - name: Update Theme Path
        run: |
          cd site
          sed -i 's|THEME = os\.path\.join.*|THEME = "../pelican-simple"|' pelicanconf.py

      - name: Build site
        run: |
          cd site
          make publish
          echo "copyninja.in" > output/CNAME

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site/output
          clean: true
          clean-exclude: |
            CNAME

